##访问根路径
#
##应用名称
#spring.application.name=springboot-demo
#debug=true
#
##访问端口号
#server.port=8080
#
##编码格式
#server.tomcat.uri-encoding=utf-8
#
##数据库相关配置
#spring.datasource.url=jdbc:mysql://110.42.253.196:3306/paylove?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC&serverTimezone=GMT%2B8
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.max-idle=10
#spring.datasource.max-wait=10000
#spring.datasource.min-idle=5
#spring.datasource.initial-size=5
#
##session生命周期
#server.servlet.session.timeout=30m
#
#logging.level.org.springframework.boot.autoconfigure: error
#
#mybatis.check-config-location=true
#mybatis.mapper-locations=classpath*:src/main/resources/mapper/*.xml
#mybatis.type-aliases-package=com.lovepay.mapper
#

#

server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://110.42.253.196:3306/paylove?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC&serverTimezone=GMT%2B8
    driver.class.name: com.mysql.jdbc.Driver
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.lovepay.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl